# Generated by Django 5.0.2 on 2024-02-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMS_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="password",
            field=models.CharField(default="user", max_length=100),
        ),
        migrations.AddField(
            model_name="participant",
            name="password",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
