# Generated by Django 5.0.2 on 2024-02-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMS_app", "0002_organizer_password_participant_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="phone_number",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone_number",
            field=models.CharField(default=""),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EMS_app.organizer",
                    ),
                ),
            ],
        ),
    ]
