# Generated by Django 5.0.2 on 2024-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMS_app", "0004_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
